[package]
name = "arma-rs-codegen"
version = "0.2.0"
authors = ["Brett <brett@mayson.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
lazy_static = "1.4"
proc-macro2 = "1.0"
quote = "1.0"
regex = "1.3"
syn = {version = "1.0", features = ["full"]}
