[package]
name = "arma-rs-macros"
version = "0.1.0"
authors = ["Brett <brett@bmandesigns.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
arma-rs = {path = "../arma-rs"}
libc = "*"
