[package]
name = "arma-rs"
description = "Arma 3 Extensions in Rust"
version = "1.13.0"
edition = "2024"
authors = ["Brett Mayson"]
repository = "https://github.com/brettmayson/arma-rs"
license = "MIT"
keywords = ["arma"]
readme = "../README.md"

[dependencies]
arma-rs-proc = { path = "../arma-rs-proc", version = "1.13.0" }
log = "0.4.33"
state = "0.6.0"
seq-macro = "0.3.6"

chrono = { version = "0.4.45", optional = true }
crossbeam-channel = { version = "0.5.16", optional = true }
libc = { version = "0.2.189", optional = true }
serde = { version = "1.0.229", features = ["derive"], optional = true }
serde_json = { version = "1.0.151", optional = true }
uuid = { version = "1.24.0", optional = true }

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.9"
features = ["libloaderapi"]

[target.'cfg(windows)'.dependencies.windows]
version = "0.62.2"
features = ["Win32_Foundation", "Win32_System_Console"]

[dev-dependencies]
trybuild = "1.0.118"

[features]
default = ["extension"]
extension = ["libc", "crossbeam-channel"]
