[package]
name = "arma-rs"
description = "Arma 3 Extensions in Rust"
version = "1.8.2"
edition = "2021"
authors = ["Brett Mayson"]
repository = "https://github.com/brettmayson/arma-rs"
license = "MIT"
keywords = ["arma"]
readme = "../README.md"

[dependencies]
arma-rs-proc = "1.7.2"
crossbeam-queue = { version = "0.3.6", optional = true }
libc = { version = "0.2.137", optional = true }
log = "0.4.16"
seq-macro = "0.3.1"

uuid = { version = "1.2.1", optional = true }
chrono = { version = "0.4.22", optional = true }
serde_json = { version = "1.0.87", optional = true }

[target.'cfg(all(target_os="windows", target_arch="x86"))'.dependencies]
link_args = "0.6.0"

[features]
default = ["extension"]
extension = ["libc", "crossbeam-queue"]
