[package]
name = "arma-rs"
description = "Arma 3 Extensions in Rust"
version = "1.3.2"
edition = "2021"
authors = ["Brett Mayson"]
repository = "https://github.com/brettmayson/arma-rs"
license = "MIT"
keywords = ["arma"]
readme = "../README.md"

[dependencies]
arma-rs-proc = "1.3.0"
crossbeam-queue = "0.3"
libc = "0.2"
log = "0.4"
lazy_static = "1.4"
regex = "1.5"
