[package]
name = "arma-rs"
description = "Arma 3 Extensions in Rust"
version = "1.7.0"
edition = "2021"
authors = ["Brett Mayson"]
repository = "https://github.com/brettmayson/arma-rs"
license = "MIT"
keywords = ["arma"]
readme = "../README.md"

[dependencies]
arma-rs-proc = "1.5.0"
crossbeam-queue = "0.3"
libc = "0.2"
log = "0.4"
lazy_static = "1.4"
regex = "1.5"

uuid = { version = "0.8", optional = true }
chrono = { version = "0.4", optional = true }
serde_json = { version = "1.0", optional = true }

[target.'cfg(all(target_os="windows", target_arch="x86"))'.dependencies]
link_args = "0.6"
