[package]
name = "arma-rs"
description = "Arma 3 Extensions in Rust"
version = "1.9.3"
edition = "2021"
authors = ["Brett Mayson"]
repository = "https://github.com/brettmayson/arma-rs"
license = "MIT"
keywords = ["arma"]
readme = "../README.md"

[dependencies]
arma-rs-proc = "1.7.2"
log = "0.4.17"
seq-macro = "0.3.2"

chrono = { version = "0.4.23", optional = true }
crossbeam-queue = { version = "0.3.8", optional = true }
libc = { version = "0.2.139", optional = true }
serde_json = { version = "1.0.91", optional = true }
uuid = { version = "1.2.2", optional = true }

[target.'cfg(all(target_os="windows", target_arch="x86"))'.dependencies]
link_args = "0.6.0"

[features]
default = ["extension"]
extension = ["libc", "crossbeam-queue"]

[build-dependencies]
skeptic = "0.13.7"

[dev-dependencies]
skeptic = "0.13.7"
