[package]
name = "arma-rs"
version = "0.1.0"
authors = ["Brett <brett@bmandesigns.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
lazy_static = "1.4"
libc = "0.2"
proc-macro2 = "0.4"
quote = "0.6"
regex = "1.3"
syn = {version = "0.15", features = ["full"]}
