[package]
name = "arma-rs"
description = "Arma 3 Extensions in Rust"
version = "1.3.0"
edition = "2021"
authors = ["Brett Mayson"]
repository = "https://github.com/brettmayson/arma-rs"
license = "MIT"
keywords = ["arma"]

[dependencies]
arma-rs-proc = { path = "../arma-rs-proc"}
crossbeam-queue = "0.3"
libc = "0.2"
log = "0.4"
